### PR TITLE
Mohammed/db changes

### PR DESCRIPTION
**Pull request by mhallaq**

### CODE REVIEW

**Review by afessha — CHANGES_REQUESTED** [review]
@mhallaq  your PR is  failing in deployment , please test it locally and makes sure everything is working.

**Comment by mhallaq** [comment]
> @mhallaq your PR is failing in deployment , please test it locally and makes sure everything is working.

@afessha : Thanks for your review, but  How can I test it locally ? could you please teach me,

**Comment by mhallaq** [comment]
@afessha : Thanks for your review, but How can I test it locally ? could you please teach me,

**Comment by mhallaq** [comment]
@afessha : Could you please review my last commit, I have done the required changes and tested locally successfully, thanks

**Review by afessha — APPROVED** [review]

**Pull request merged**
